spring.application.name=io-service
server.port=8083

spring.datasource.url=${APP_DB_URL:jdbc:postgresql://localhost:5432/app_db}
spring.datasource.username=${APP_DB_USERNAME:postgres}
spring.datasource.password=${APP_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
